<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">
  <link rel="stylesheet" href="css/reset.css">
  <link rel="stylesheet" href="css/jquery-ui.structure.min.css">
  <link rel="stylesheet" href="css/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="css/style.css">
  <title>Memory</title>
</head>
<body id="body">
  <header>
    <h1>Jeu de mémoire</h1>
  </header>
  <main>
    <div id="tentative">
      <h1>Nombre de tentatives</h1>
      <p id="nbTentative">0</p>
    </div>
    <div id="plateau">

    </div>
    <div id="progress">
        <div class="progress-label">Lancement de la partie dans 5 secondes !</div>
        <div id="progressbar"></div>
    </div>
  </main>
  <footer>

  </footer>
  <script type="text/javascript" src="js/jquery.js"></script>
  <script type="text/javascript" src="js/jquery-ui.min.js"></script>  
  <script type="text/javascript" src="js/app.js"></script>
</body>
</html>
